import dayjs from "dayjs";
import { WorkorderResponseType } from "../../types";

export const fetchWorkordersMock: WorkorderResponseType = {
  count: 2,
  next: null,
  previous: null,
  results: [
    {
      url: "http://localhost:8000/assetworkorders/101/?format=api",
      id: "101",
      assets: [5119, 5120, 5121],
      assignee: {
        email: "",
        first_name: "Beaconsfield",
        id: "23",
        last_name: "",
        name: "Beaconsfield ",
        organizations: [],
      },
      assignedContact: undefined,
      checklists: [10, 15, 18],
      assigned_by: 5,
      overdue: false,
      created: new Date("2022-05-03T00:39:06.434995Z"),
      updated: new Date("2022-09-22T12:51:07.619752Z"),
      name: "Maintenance annuelle - 2021 - Toit Hôtel de ville",
      description: "Ventilateur d'évacuation. Maintenance par Navada.",
      status: {
        id: 3,
        name: "In_Progress",
        description: "In Progress",
        orderInList: 3,
      },
      workOrderPriority: {
        workOrderPriorityId: 1,
        name: "Normal",
        description: "Normal",
        orderInList: 1,
      },
      duedate: dayjs("2021-12-22"),
      scheduleddate: new Date("2022-09-13"),
      type: "test",
    },
    {
      url: "http://localhost:8000/assetworkorders/102/?format=api",
      id: "102",
      assets: [5120],
      assignee: {
        email: "",
        first_name: "Beaconsfield",
        id: "23",
        last_name: "",
        name: "Beaconsfield ",
        organizations: [],
      },
      assignedContact: undefined,
      checklists: [15],
      assigned_by: 5,
      overdue: true,
      created: new Date("2022-05-03T00:40:57.780395Z"),
      updated: new Date("2022-09-22T13:02:35.773577Z"),
      name: "Maintenance Annuelle - 2022 - BA-3-MUAI-0 (R)",
      description: "Unité d'apport d'air neuf.Maintenance par Navada",
      status: {
        id: 2,
        name: "Ready",
        description: "Ready",
        orderInList: 2,
      },
      workOrderPriority: {
        workOrderPriorityId: 1,
        name: "Normal",
        description: "Normal",
        orderInList: 1,
      },
      duedate: dayjs("2022-09-14"),
      scheduleddate: new Date("2022-03-02"),
      type: "test",
    },
  ],
};
